### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by stvdwtt** [ORNL/CabanaPF#1]
Here are a list of suggestions for cleaning up the code from its state in !7. None of these involve correctness, but are more focused on usability. These changes, if we decide to make them, can be after the 0.1 release if necessary.

- [x] Users will want to vary `CabanaPF::PFHub1aBase::END_TIME` since that isn't given in the spec (and we've discussed this in terms of the PFHub upload). It should be an option at construction (a default of 250 is ok).
- [x] The "PerformanceRuns" executable should also be able to have a user-set time step and/or number of time steps so you can do individual runs like the "PFHub1a_Benchmark" and "PFHub1a_Periodic" collection of calculations.
- [x] The `main` functions the "Benchmark" cases are only 40 lines, but they are identical except for which child of `PFHub1aBase` they use. It seems more intuitive to merge them into one function with a selection statement for which case to run based on e.g. a command line argument. Maybe you could do something fancy with base class pointers so that you only have to do that selection statement once? (Not something that I'm very strong with.)
- [x] I'm not sure that using `fft` for a forward transform and `ifft` for an inverse transform in `CabanaPF::PFVariables` is the most intuitive, unless that's standard elsewhere. I prefer the interface that FFTW and heFFTe use, where you're specifying "forward" or "inverse". I'd prefer `fft_forward` and `fft_inverse`.
~Since the code is written to work in both 2 and 3 dimensions, it should have a 3D test~

**Comment by DavidJoy8** [comment]
I think the 5th bullet should be moved to Issue #3 , turning it into the "3D issue."  This issue is a bit over-scoped in my opinion.
